const pathsCompletelyWhiteListed=[
  "/product-display/flowers/",
  "/productpages/product-display/flowers/",
  "/resources/img/",
  "/display/userDisplay/",
  "/admin/",
  "/client/",
  "/notlogged/",
  "/vendor/",
  "/adminpages/"
]
const whitelist = [
  "/productpages/myshoppingcart.html",
  "/productpages/mygarden.html",
  "/productpages/placeOrder.html",
  "/productpages/product.html",
  "/productpages/product.html",
  "/productpages/removeFlower.html",
  "/productpages/search.html",
  "/productpages/plantFlower.html",
  '/accountpages/myhomes/',
  "/productpages/removeFlower.html",
  "/accountpages/myhomes/product.html",
  "/productpages/product-display/flowers_for_debug.js",
  "/productpages/product-display/products-grid.js",
  "/productpages/product-display/search.js",
  "/productpages/search.html",
  "/productpages/product.html",
  "/accountpages/myhomes/homePageClient.html",
  "/accountpages/myhomes/homePageVendor.html",
  "/accountpages/myhomes/index.html",
  "/accountpages/mynotifications/MyNotifications.html",
  "/accountpages/myaccount/MyAccountNotLoggedIn.html",
  "/accountpages/myaccount/MyAccount.html",
  "/404.html",
  "/AdminPage.html",
  "/ChangePassword.html",
  "/homePageClient.html",
  "/homePageVendor.html",
  "/index.html",
  "/mygarden.html",
  "/myshoppingcart.html",
  "/placeOrder.html",
  "/plantFlower.html",
  "/product.html",
  "/removeFlower.html",
  "/removeUser.html",
  "/Documentation.html",
  "/search.html",
  "/userInfo.html",
  "/accountpages/MyAccount.html",
  "/accountpages/MyAccountNotLoggedIn.html",
  "/accountpages/mynotifications/MyNotifications.html",
  "/login+register/formValidation.js",
  "/login+register/login.html",
  "/login+register/login_register_logic.js",
  "/login+register/register.html",
  "/product-display/flowers_for_debug.js",
  "/product-display/products-grid.js",
  "/product-display/search.js",
  "/resources/css/formContainer.css",
  "/resources/css/homePageVendor.css",
  "/resources/css/menustyle.css",
  "/resources/css/mygarden.css",
  "/resources/css/notifications_styles.css",
  "/resources/css/plantFlower.css",
  "/resources/css/product-card.css",
  "/resources/css/productpage-styles.css",
  "/resources/css/profileContainer.css",
  "/resources/css/search.css",
  "/resources/css/shoppingcart.css",
  "/resources/css/style.css",
  "/resources/js/app.js",
  "/resources/js/config.js",
  "/resources/js/export.js",
  "/resources/js/menuByRole.js",
  "/resources/js/mynotifications.js",
  "/resources/js/navbar-script.js",
  "/resources/js/role.js",
  "/resources/js/shoppingCart.js",
  "/resources/js/urlHelper.js",
  "/resources/js/admin/createUserCard.js",
  "/resources/js/admin/deleteUser.js",
  "/resources/js/admin/getAllUsers.js",
  "/resources/js/client/addToCartButton.js",
  "/resources/js/client/add-to-watchlist.js",
  "/resources/js/client/getSearchFlowers.js",
  "/resources/js/loggedUser/changeData.js",
  "/resources/js/notifications/deleteNotification.js",
  "/resources/js/notlogged/getProducts.js",
  "/resources/js/vendor/addFlower.js",
  "/resources/js/vendor/deleteFlowers.js",
  "/resources/js/vendor/getFlowers.js",
  "/resources/js/vendor/moveToSale.js",
  '/resources/notification-icon.png'
];
whitelist.push("/","/favicon.ico",
  "/resources/favicon.ico",
  "/resources/icon.png",
  "/resources/icon.svg",
  "/login", "/formValidation.js", "login_register_logic.js",
  "/register", "/authentification/extractPayLoad.js");
let whitelist_nocase= whitelist.map(value => value.toLowerCase());
let pathsWhite_nocase=pathsCompletelyWhiteListed.map(value => value.toLowerCase());

function isWithinWhitePath(str){
  for(var pathW of pathsWhite_nocase)
    if(str.toLowerCase().startsWith(pathW))
      return true;
  return false;
}

const fileMap = {
  '/adminpages/display/userDisplay/defaultUser.png':'/adminpages/userDisplay/defaultUser.png',
  '/adminpages/adminpages/userDisplay/defaultUser.png':'/adminpages/userDisplay/defaultUser.png',
  '/homePageClient.html': '/accountpages/myhomes/homePageClient.html',
  '/homePageVendor.html': '/accountpages/myhomes/homePageVendor.html',
  '/adminpages/product.html':'/productpages/product.html',
  '/index.html': '/accountpages/myhomes/index.html',
  '/':'/accountpages/myhomes/index.html',
  '/accountpages/MyNotifications.html': '/accountpages/mynotifications/MyNotifications.html',
  '/accountPages/MyAccount.html':'/accountpages/myaccount/MyAccount.html',
  '/MyAccount.html':'/accountpages/myaccount/MyAccount.html',
  '/MyAccountNotLoggedIn.html':'/accountpages/myaccount/MyAccountNotLoggedIn.html',
  '/accountpages/MyAccount.html':'/accountpages/myaccount/MyAccount.html',
  '/accountpages/MyAccountNotLoggedIn.html':'/accountpages/myaccount/MyAccountNotLoggedIn.html',
  '/AdminPage.html':'/adminpages/AdminPage.html',
  '/removeFlower.html': '/productpages/removeFlower.html',
  '/adminpages/removeFlower.html':'/productpages/removeFlower.html',
  '/removeUser.html':'/adminpages/removeUser.html',
  '/userInfo.html':'/adminpages/userInfo.html',
  '/mygarden.html':'/productpages/mygarden.html',
  '/myshoppingcart.html':'/productpages/myshoppingcart.html',
  '/placeOrder.html':'/productpages/placeOrder.html',
  '/accountpages/myhomes/':'/accountpages/myhomes/index.html',
  '/plantFlower.html':'/productpages/plantFlower.html',
  '/product.html':'/productpages/product.html',
  '/search.html':'/productpages/search.html',
  '/product-display/flowers_for_debug.js':'/productpages/product-display/flowers_for_debug.js',
  '/product-display/flowersflower1.jpg':'/productpages/product-display/flowersflower1.jpg',
  '/product-display/products-grid.js':'/productpages/product-display/products-grid.js',
  '/product-display/search.js':'/productpages/product-display/search.js',
  '/accountpages/myhomes/product.html':'/productpages/product.html',
};

module.exports ={fileMap, whitelist, whitelist_nocase, pathsWhite_nocase, pathsCompletelyWhiteListed, isWithinWhitePath} ;

